---
- name: (re)start znc
  docker_container:
    name: znc
    restart: yes
    image: "{{ docker_image }}"
    volumes:
      - "{{ docker_volume }}"
    exposed:
      - "7000"
    ports:
      - "7000:7000"
