---
Layout/AlignArray:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false
