---
- name: taskd
  hosts: digitalocean
  become: true
  become_user: app
  tasks:
    - name: create taskd data directory
      file:
        path: /home/app/taskd
        state: directory
      register: create_taskd_dir_result
    - name: initialize taskd data directory
      docker_container:
        name: taskd_init
        image: katsuya94/taskd:latest
        volumes:
          - /home/app/taskd:/var/taskd
        command: taskd init
      when: create_taskd_dir_result.changed
    - name: change ownership of taskd config
      file:
        path: /home/app/taskd/config
        owner: app
      become_user: root
    - name: create taskd pki directory
      file:
        path: /home/app/taskd/pki
        state: directory
    - name: configure taskd
      lineinfile:
        path: /home/app/taskd/config
        regexp: "^{{ item.key | regex_escape }}="
        line: "{{ item.key }}={{ item.value }}"
      with_dict:
        log: "-"
        server.cert: /var/taskd/pki/server.cert.pem
        server.key: /var/taskd/pki/server.key.pem
        server: "0.0.0.0:53589"
    - name: copy pki files
      copy:
        src: "taskd/{{ ansible_host }}-{{ item }}"
        dest: "/home/app/taskd/pki/{{ item }}"
      with_items:
        - server.key.pem
        - server.cert.pem
    - name: start taskd
      docker_container:
        name: taskd
        image: katsuya94/taskd:latest
        volumes:
          - /home/app/taskd:/var/taskd
        exposed:
          - "53589"
        ports:
          - "53589:53589"
