---
- name: taskd
  hosts: digitalocean
  become: true
  become_user: app
  vars_files:
    - vars/docker.yml
  vars:
    docker_run: "docker run -v {{ docker_volume }} {{ docker_image }}"
    csr_filename: "{{ ansible_date_time.iso8601_micro | to_uuid }}.csr"
  tasks:
    - name: pull image
      docker_image:
        name: "{{ docker_image }}"
        force: yes
    - name: create taskd data directory
      file:
        path: "{{ directory }}"
        state: directory
      register: create_taskd_data_directory_result
    - name: initialize taskd data directory
      command: "{{ docker_run }} taskd init"
      when: create_taskd_data_directory_result.changed
    - name: create taskd pki directory
      file:
        path: "{{ directory }}/pki"
        state: directory
    - name: configure taskd
      lineinfile:
        path: "{{ directory }}/config"
        regexp: "^{{ item.key | regex_escape }}="
        line: "{{ item.key }}={{ item.value }}"
      with_dict:
        log: "-"
        ca.cert: /var/taskd/pki/ca.cert.pem
        server.cert: /var/taskd/pki/server.cert.pem
        server.key: /var/taskd/pki/server.key.pem
        server.crl: /var/taskd/pki/crl.pem
        server: "0.0.0.0:53589"
        debug: "off"
        debug.tls: 0
      become_user: root
    - name: copy pki
      copy:
        src: "{{ item.key }}"
        dest: "{{ item.value }}"
        remote_src: yes
      with_dict:
        "/home/app/pki/server.key.pem": "{{ directory }}/pki/server.key.pem"
        "/home/app/pki/server.cert.pem": "{{ directory }}/pki/server.cert.pem"
        "/home/app/pki/ca.cert.pem": "{{ directory }}/pki/ca.cert.pem"
        "/home/app/pki/crl.pem": "{{ directory }}/pki/crl.pem"
    - name: add organization
      command: "{{ docker_run }} taskd add org Public"
      args:
        creates: "{{ directory }}/orgs/Public"
      become_user: root
    - name: add user
      command: "{{ docker_run }} taskd add user Public kacchan"
      args:
        creates: "{{ directory }}/orgs/Public/users/*"
      become_user: root
    - import_tasks: tasks/bounce.yml
