---
- name: taskd
  hosts: digitalocean
  become: true
  become_user: app
  vars:
    organizations:
      - name: Public
    users:
      - name: kacchan
        organization: Public
    directory: /home/app/taskd
    docker_volume: "{{ directory }}:/var/taskd"
    docker_image: katsuya94/taskd:latest
    docker_run: "docker run -v {{ docker_volume }} -it"
  tasks:
    - name: create taskd data directory
      file:
        path: "{{ directory }}"
        state: directory
      register: create_taskd_dir_result
    - name: initialize taskd data directory
      command: "{{ docker_run }} taskd init"
      when: create_taskd_dir_result.changed
    - name: change ownership of taskd config
      file:
        path: "{{ directory }}/config"
        owner: app
      become_user: root
    - name: create taskd ansible directory
      file:
        path: "{{ directory }}/ansible"
        state: directory
    - name: create taskd pki directory
      file:
        path: "{{ directory }}/pki"
        state: directory
    - name: configure taskd
      lineinfile:
        path: "{{ directory }}//config"
        regexp: "^{{ item.key | regex_escape }}="
        line: "{{ item.key }}={{ item.value }}"
      with_dict:
        log: "-"
        server.cert: /var/taskd/pki/server.cert.pem
        server.key: /var/taskd/pki/server.key.pem
        server: "0.0.0.0:53589"
    - name: copy pki files
      copy:
        src: "taskd/{{ ansible_host }}-{{ item }}"
        dest: "{{ directory }}/pki/{{ item }}"
      with_items:
        - server.key.pem
        - server.cert.pem
    - name: add organizations
      command: "{{ docker_run }} taskd add org {{ item.name }}"
      args:
        creates: "{{ directory }}/ansible/{{ item.name }}.organization"
      with_items: organziations
    - name: add users
      command: "{{ docker_run }} taskd add user {{ item.organization }} {{ item.name }}"
      args:
        creates: "{{ directory }}/ansible/{{ item.name }}.{{ item.organization }}.user"
      with_items: users
    - name: start taskd
      docker_container:
        name: taskd
        image: "{{ docker_image }}"
        volumes:
          - "{{ docker_volume }}"
        exposed:
          - "53589"
        ports:
          - "53589:53589"
